[package]
name = "apx"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-kinesis = "1.49.0"
axum = "0.7.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }

