[package]
name = "apx"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.5.9", features = ["behavior-version-latest"] }
aws-sdk-kinesis = "1.49.0"
axum = "0.7.7"
lambda-extension = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
hyper = "0.14.31"

